import Head from 'next/head';
import Image from 'next/image';
import QRCode from '../components/qrcode';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>QRCode Generator</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/images/favicon-32x32.png" />
			</Head>
			<main className={styles.main}>
				<QRCode />
			</main>
		</div>
	);
}
